const API={dashboard:"../data/data.json"};
let indexData=null,operatorCache={};
const $id=id=>document.getElementById(id);
function esc(v){return String(v??"—").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));}
function badge(v){if(v===true)v="TRUE";if(v===false)v="FALSE";const s=String(v??"—"),u=s.toUpperCase();let c="secondary";if(["SUCCESS","200 OK","CONFIRMED","AVAILABLE","ДОСТУПЕН","TRUE"].includes(u))c="success";else if(["FAILED","FAIL","DOWN","NOT PROVEN","NOT_PROVEN","НЕДОСТУПЕН","FALSE"].includes(u))c="danger";else if(["TIMEOUT","NOT OBSERVED","NOT_OBSERVED"].includes(u))c="warning";return '<span class="badge text-bg-'+c+'">'+esc(s)+'</span>';}
function makeNav(){const items=[{name:"Все операторы",short_name:"all"}].concat(indexData.operators);for(const host of [$id("desktopSide"),$id("mobileSide")]){host.innerHTML='<div class="small text-uppercase text-secondary mb-2">Операторы</div>'+items.map(x=>'<button class="nav-link w-100 text-start mb-1 border-0 rounded '+(x.short_name==="all"?"active":"")+'" data-op="'+esc(x.short_name)+'">'+esc(x.name||x.short_name)+'</button>').join("");host.querySelectorAll("[data-op]").forEach(b=>b.onclick=()=>selectOperator(b.dataset.op));}}
function card(title,value,sub){return '<div class="col-6 col-xl-3"><div class="card metric"><div class="card-body"><div class="text-secondary small">'+esc(title)+'</div><div class="fs-3 fw-semibold">'+esc(value)+'</div><div class="small text-secondary">'+esc(sub||"")+'</div></div></div></div>';}
function renderSummary(ops){const tested=ops.filter(o=>o.status&&o.status!=="NOT_TESTED").length,ok=ops.filter(o=>["CONFIRMED","SUCCESS"].includes(String(o.status).toUpperCase())).length; $id("summary").innerHTML=card("Операторов",ops.length,"в конфигурации")+card("Измерено",tested,"имеют результат")+card("Подтверждено",ok,"IP/application")+card("Не протестировано",ops.length-tested,"ожидают измерения");}
function rowsFor(op){const r=op.result||{},c=op.connectivity||{},t=c.tcp||{};return [
{test:"IP connectivity",result:r.ip_connectivity,details:"TCP 22/8080"},
{test:"Application",result:r.application_connectivity,details:"HTTP/8080"},
{test:"BGP reachability",result:r.bgp_reachability,details:"RIPE RIS"},
{test:"MPLS",result:r.mpls_observed,details:"Internal routing evidence"},
{test:"Direct physical interconnect",result:r.direct_physical_interconnect,details:"Not inferred from BGP"},
{test:"Specific IX path",result:r.specific_ix_path,details:"Requires explicit evidence"},
{test:"Internet transit",result:r.internet_transit,details:"Not inferred"},
{test:"Exact physical path",result:r.exact_physical_path,details:"Not inferred"}];}
function renderMatrix(ops){const rows=[];for(const op of ops){for(const x of rowsFor(op))rows.push({operator:op.operator?.short_name||op.short_name||op.name,test:x.test,result:badge(x.result),details:x.details});}$("#matrix").bootstrapTable("destroy").bootstrapTable({columns:[{field:"operator",title:"Оператор"},{field:"test",title:"Проверка"},{field:"result",title:"Результат",formatter:v=>v},{field:"details",title:"Основание"}],data:rows});}
function renderRecent(ops){const rows=ops.map(op=>({date:op.measurement?.date||"—",operator:op.operator?.short_name||op.short_name||op.name,status:badge(op.measurement?.status||op.status),ip:op.operator?.tested_ip||op.tested_ip||"—"}));$("#recent").bootstrapTable("destroy").bootstrapTable({columns:[{field:"date",title:"Дата"},{field:"operator",title:"Оператор"},{field:"ip",title:"IP источника"},{field:"status",title:"Статус",formatter:v=>v}],data:rows.sort((a,b)=>String(b.date).localeCompare(String(a.date)))});}
function hopLabel(h){return (h.ip||"*")+(h.asn?" ("+h.asn+")":"");}
function renderDetails(op){const r=op.result||{},t=op.traceroute||{};$id("details").innerHTML='<div class="row g-3"><div class="col-md-6"><dl class="row mb-0"><dt class="col-6">IP</dt><dd class="col-6">'+esc(op.operator?.tested_ip)+'</dd><dt class="col-6">ASN</dt><dd class="col-6">'+esc(op.operator?.asn)+'</dd><dt class="col-6">Prefix</dt><dd class="col-6">'+esc(op.operator?.prefix)+'</dd><dt class="col-6">Дата</dt><dd class="col-6">'+esc(op.measurement?.date)+'</dd></dl></div><div class="col-md-6"><dl class="row mb-0"><dt class="col-6">IP connectivity</dt><dd class="col-6">'+badge(r.ip_connectivity)+'</dd><dt class="col-6">Application</dt><dd class="col-6">'+badge(r.application_connectivity)+'</dd><dt class="col-6">BGP</dt><dd class="col-6">'+badge(r.bgp_reachability)+'</dd><dt class="col-6">Traceroute hops</dt><dd class="col-6">'+esc((t.hops||[]).map(hopLabel).join(" → "))+'</dd></dl></div></div>'; }
async function loadJson(url){const response=await fetch(url+"?t="+Date.now());if(!response.ok)throw new Error("HTTP "+response.status);const data=await response.json();if(data.schema_version!=="1.0")throw new Error("Unsupported schema version: "+(data.schema_version||"unknown"));return data;}
async function selectOperator(short){document.querySelectorAll("[data-op]").forEach(b=>b.classList.toggle("active",b.dataset.op===short));if(short==="all"){const ops=await Promise.all(indexData.operators.filter(x=>x.status!=="NOT_TESTED").map(x=>loadJson("../data/"+x.file)));$id("title").textContent="Все операторы";renderSummary(indexData.operators);renderMatrix(ops);renderRecent(ops);$id("details").innerHTML="Выберите оператора слева для подробностей.";return;}const meta=indexData.operators.find(x=>x.short_name===short);if(!meta)return;const op=operatorCache[short]||(operatorCache[short]=await loadJson("../data/"+meta.file));$id("title").textContent=meta.name;renderSummary([meta]);renderMatrix([op]);renderRecent([op]);renderDetails(op);}
async function loadDashboard(){try{indexData=await loadJson(API.dashboard);$id("target").textContent=indexData.project.measurement_target.name+" · "+indexData.project.measurement_target.ip+" · "+indexData.project.measurement_target.asn;makeNav();await selectOperator("all");$id("loadStatus").textContent="OK";$id("loadStatus").className="badge text-bg-success";}catch(e){$id("error").textContent="Dashboard loading error: "+e.message;$id("error").classList.remove("d-none");$id("loadStatus").textContent="ERROR";$id("loadStatus").className="badge text-bg-danger";console.error(e);}}
document.addEventListener("DOMContentLoaded",loadDashboard);
